### ISSUE TITLE
makeJSON protection level

### ISSUE THREAD

**Issue by jdmcd** [vapor/json#22]
When trying to do something like `Model.all().makeJSON()` an error is thrown with the warning, `makeJSON is inaccessible due to internal protection level`

**Comment by tanner0101** [comment]
This looks like it could be related to: https://github.com/vapor/json/pull/20

What version of JSON do you have in your project?

**Comment by jdmcd** [comment]
1.0.2

**Comment by tanner0101** [comment]
Clean and rebuild to upgrade to 1.0.3 and your problem should be fixed.

**Comment by jdmcd** [comment]
Will do! Thanks
