### ISSUE TITLE
Keys containing periods result in nested dictionaries

### ISSUE THREAD

**Issue by shanemcquillan** [vapor/json#58]
Here's a simple example of this:

    var test = JSON()
    try test.set("my.nested.key", "test")
    print(test)

Output:
    JSON(wrapped: [my: [nested: [key: test]]], context: JSON.JSONContext)

Expected:
    JSON(wrapped: [my.nested.key: test], context: JSON.JSONContext)

I'm not sure whether this is a bug or a feature, but I can't find any documentation on it, or how to workaround it.

**Comment by tanner0101** [comment]
If you use `DotKey("my.nested.key")` they won't be interpreted as nested. :)

**Comment by shanemcquillan** [comment]
That did it, many thanks for the speedy reply.
