### ISSUE TITLE
Quotes in strings are not escaped

### ISSUE THREAD

**Issue by vzsg** [vapor/json#59]
It seems that the serialize function is [over-optimized](https://github.com/vapor/json/blob/master/Sources/JSON/JSON%2BSerialize.swift#L16) for Strings. If the input contains double quotes, these are not escaped with a backslash, resulting in an invalid JSON output.

IOW, encoding the `foo "bar"` String should result in `"foo \"bar\""`, but instead `"foo "bar""` is returned.

I also added a failing test case to reproduce this.

**Comment by vzsg** [comment]
Can this get a tag?

**Comment by tanner0101** [comment]
sorry for the delay: https://github.com/vapor/json/releases/tag/2.2.1
