### ISSUE TITLE
App crashes when trying to get big numbers as int

### ISSUE THREAD

**Issue by koraykoska** [vapor/json#66]
### Issue and Steps to Reproduce
This issue somehow affects [vapor](https://github.com/vapor/vapor) the most and actually comes from [node](https://github.com/vapor/node) but as `JSON` is mostly used on top of node and I haven't tested it with other node implementations, I am opening it here.

`StructuredData` has some problems dealing with big numbers (Numbers too big to be represented by a 64 bit integer). Because of that, applications trying to fetch numbers from `JSON` (or any other `StructuredData` implementing apis) will crash.

A very simple example which demonstrates how severe this issue is can be seen in the following example, which is a vapor `POST` route.

```Swift
post("json") { req in
    guard let i = req.json?["int"]?.int else {
        return "kind of also a success"
    }

    return "success. Int: \(i)"
}
```

This example does something which is used by many vapor applications. It just fetches an integer from a json HTTP request.

**Test Cases:**

* POST /json - Body: { "int": 1 }
-> Response: success. Int: 1

* POST /json - Body: {}
-> Response: kind of also a success

* POST /json - Body: { "int": 10000000000000000000 }
-> **No Response, App crashes**

The error is the following:

> Double value cannot be converted to Int because the result would be greater than Int.max

It is raised because of an invalid conversion from `Double` to `Int` (Double can store much higher values than Int). See [the relevant piece of code](https://github.com/vapor/node/blob/master/Sources/Node/Number/Number.swift#L78).

The same applies to `UInt` and it happens really because of this line:

`return Int(d)`

where d is a `Double` which was not checked to be `Int.max` or less before.

### Impact
Because of this malicious users can send requests with big numbers to vapor backed applications to crash them. This issue needs to be solved and released in a critical bug fix update ASAP.

### Proposed Solution
Testing the number to be less than or equal `Int.max` (or `UInt.max`) should work.    
The only thing we need to discuss is whether we want to return `nil` if the number is too high to fit an `Int` or simple `Int.max`.    
I personally like the solution with returning `nil`, as this is what happens. The developer requests an `Int` and there is no representable value there. Returning `Int.max` may be problematic in some situations for developers.

Whatever we decide, it is definitely better than a crash.

Once you give me your ok I am happy to submit a pull request to `node` and add some test cases.

**Comment by koraykoska** [comment]
See this sample vapor app which implements a simple post route to `/json` just like shown above.
[json_crash.tar.gz](https://github.com/vapor/json/files/1482011/json_crash.tar.gz)

**Comment by vzsg** [comment]
This is probably caused by the fact that StructuredData doesn't support Int64 at all.

If you can make the jump to Swift 4, you should leverage Codable and forget that the JSON type ever existed.

**Comment by koraykoska** [comment]
@vzsg I will definitely have a look through Codable. Thanks for the hint.

But nevertheless we need to fix this because thousands of apps are using `JSON` right now and with the current version crashing their web servers may really be possible with nothing more than a simple request.

**Comment by vzsg** [comment]
Yeah, that's indeed pretty bad. The error is actually coming from the Number.swift in the Node module, where there are some random safeguards against overflow, but not in the double case.

@tanner0101 could you take a look at this please?

**Comment by tanner0101** [comment]
how does this look: https://github.com/vapor/node/pull/97
