### ISSUE TITLE
Vapor 3 Support !

### ISSUE THREAD

**Issue by fadylateef** [vapor/json#70]
I can't use the library for Vapor 3.0 . Its native |Content| protocol needs JSON mapping each time to handle json data.
Could you please support Vapor 3.0

**Comment by 0xTim** [comment]
@fadylateef support for Vapor 3 won't happen since it relied on a _ton_ of hacks to make it work that have all been solved by Codable. What issues are you having with `Content`?

**Comment by fadylateef** [comment]
I think it was easier  `return JSON(node: ["name" : "Tim"]`
than creating a new struct and return it for simple return message.
```
struct nameModel : Content {
var name : String
}

return nameModel(name: "Tim")
```
